#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evmfs.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* LibEVM writable globals */

  /* global
       wallet_name:
         writable */


/* eslint-disable
     no-unused-vars */

/* eslint
     no-undef:
       "error" */
/* eslint
     no-unused-vars: [
       "error",
       { "vars":
           "local" }
     ] */

const
  _libcrash =
    require(
      "crash-js");
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _process_exit */
const
  _process_exit =
    _libcrash._process_exit();
const
  _libevmfs_module =
    require(
      "./libevmfs");
/* global
     _evmfs */
const
  _evmfs =
    _libevmfs_module._evmfs;
/* global
     _ccget */
/* exported
     _ccget */
const
  _ccget =
    _libevmfs_module._ccget;
/* global
     _check */
/* exported
     _check */
const
  _check =
    _libevmfs_module._check;
/* global
     _get */
/* exported
     _get */
const
  _get =
    _libevmfs_module._get;
/* global
     _index */
/* exported
     _index */
const
  _index =
    _libevmfs_module._index;
/* global
     _lock */
/* exported
     _lock*/
const
  _lock =
    _libevmfs_module._lock;
/* global
     _lengthlock*/
/* exported
 *   _lengthlock*/
const
  _lengthlock =
    _libevmfs_module._lengthlock;
/* global
     _publish*/
/* exported
     _publish*/
const
  _publish =
    _libevmfs_module._publish;
/* global
     _publish_bulk */
/* exported
     _publish_bulk */
const
  _publish_bulk =
    _libevmfs_module._publish_bulk;
/* global
     _verify */
/* exported
     _verify */
const
  _verify =
    _libevmfs_module._verify;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "evmfs.js";
  /* global
       app_opts:
         writable */
  app_opts =
    [];
  /* global
       retries_max:
         writable */
  retries_max =
    "";
  /* global
       api_key_path:
         writable */
  api_key_path =
    "";
  /* global
       target_network:
         writable */
  target_network =
    "";
  /* global
       deployments_dir:
         writable */
  deployments_dir =
    "";
  /* global
       fs_version:
         writable */
  fs_version =
    "";
  /* global
       rpc_selection:
         writable */
  rpc_selection =
    "";
  /* global
       contract_address:
         writable */
  contract_address =
    "";
  /* global
       contract_abi_path:
         writable */
  contract_abi_path =
    "";
  /* global
       contract_bytecode_path:
         writable */
  contract_bytecode_path =
    "";
  /* global
       contract_compiler_output_path:
         writable */
  contract_compiler_output_path =
    "";
  /* global
       method_objects:
         writable */
  method_objects =
    {};
  /* global
       publication_namespace:
         writable */
  publication_namespace =
    "";
  /* global file_hash:
       writable */
  file_hash =
    "";
  /* global
       index_start:
         writable */
  index_start =
    "";
  /* global
       index_end:
         writable */
  index_end =
    "";
  /* global
       checkpoint_file_path:
         writable */
  checkpoint_file_path =
    "";
  /* global
       chunks_files_paths:
         writable */
  chunks_files_paths =
    [];
  /* global
       quiet:
         writable */
  quiet =
    "";
}

function
  _overrides_set() {
  if ( rpc_selection == "" ) {
    rpc_selection =
      "kirsh";
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "",
      "Ethereum Virtual Machine File System",
      "",
      "Usage:",
      `  ${app_name}`,
      "    [options]",
      "    <command>",
      "    ( [command-args] )",
      "",
      "  commands:",
      "    get",
      "      <resource-uri>",
      "    publish",
      "      <file-path>",
      "",
      "  networks:",
      `    '${_target_networks}`',
      "",
      "  options:",
      "",
      "    -m <call-method>          It can be 'standalone', 'bulk' or",
      "                              'simulate'",
      `                              Default: ${call_method}`,
      "",
      "    -i <index-network>        EVM Network for the CrossChainFileSystem and
      "                              the LengthLock contracts.",
      `                              Default: ${index_network}`,
      "",
      "    -r <retries-max>          Maximum number of retries before",
      "                              failing.",
      "                              Default: ${retries_max}`,
      "",
      "    -T <call-timeout>         Maximum number of milliseconds before",
      "                              declaring the call failed.",
      `                              Default: ${call_timeout}`,
      "",
      "    -P <tasks-parallel>       How many calls tasks perform at any",
      "    --tasks-parallel <num>    given time.",
      `                              Default: ${tasks_parallel}`,
      "",
      "  get options:",
      "",
      "    -o <output-file>          Name of the file in which to save",
      "                              the downloaded resource.",
      `                              Default: ${output_file}`,
      "",
      "  publish options:",
      "",
      "    -L                        Skip check and publish and only lock",
      "                              the file.",
      `                              Default: ${lock_only}`,
      "",
      "    -l <chunk-length>         Length of the encoded chunk.",
      "                              It can be different whether",
      "                              you are using GNU Bash or",
      "                              Javascript version of Encoding",
      "                              Tools.",
      "                              On EVM networks one can write up",
      "                              around 24.000 characters but on",
      "                              some networks it seems it's not possible",
      "                              to spend the amount of gas needed to",
      "                              write that much.",
      `                              Default: ${chunk_length}`,
      "",
      "  contract options:",
      "",
      "    -A <fs-address>           Address of the EVM file system",
      "                              on the network.",
      `                              Default: ${fs_address}`,
      "",
      "    -C <ccfs-address>         Address of the CrossChainFileSystem",
      "                              contract on the network.",
      `                              Default: ${ccfs_address}`,
      "",
      "    -V <fs-version>           Version of the target EVM file",
      "                              system.",
      `                              Default: ${fs_version}`,
      "",
      "  libevm options:",
      "",
      "    -u                        Whether to retrieve file system",
      "                              address from user directory or",
      "                              custom deployment.",
      `                              Default: ${user_level}`,
      "",
      "    -d <deployments-dir>      Contracts deployments directory.",
      `                              Default: ${deployments_dir}`,
      "",
      "    -n <network>              EVM network names. Use either name",
      "                              or Chain ID.",
      `                              Default: ${target_networks}`,
      "  credentials options:",
      "    -N <wallet-name>          Wallet name.",
      `    --wallet-name <name>      Default: ${wallet_name}`,
      "",
      "    -w <wallet-path>          Wallet path.",
      `    --wallet-path <path>      Default: ${wallet_path}`,
      "",
      "    -p <wallet-password>      Wallet password.",
      `    --wallet-password <path>  Default: ${wallet_password}`,
      "",
      "    -s <wallet-seed>          Wallet seed path.",
      `    --wallet-seed <seed>      Default: ${wallet_seed}`,
      "",
      "    -k <api-key>              Etherscan-like service key.",
      `    --api-key <path>          Default: ${api_key}`,
      "",
      "  application options:",
      "",
      "    -W <cache-dir>            Work directory.",
      `                              Default: ${cache_dir}`,
      "",
      "    -h, --help               This message.",
      "",
      "    -c, --color              Enable color output",
      "",
      "    -v, --verbose            Enable verbose output",
    ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  _process_exit(
    _exit_code);
}

function 
  _cmdline_parse() {
  quiet = 
    "y";

}

if ( _cmdline_check(
       "evmfs.js") ) {
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    retries_max,
    api_key_path,
    target_network,
    deployments_dir,
    fs_version,
    rpc_selection,
    contract_address,
    contract_abi_path,
    contract_bytecode_path,
    contract_compiler_output_path,
    method_objects,
    publication_namespace,
    file_hash,
    index_start,
    index_end,
    checkpoint_file_path,
    chunks_files_paths,
  ];
  _evmfs.apply(
    null,
    app_opts);
}
