#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    -----------------------------------------------------------
 *     evmfs.js
 *     -----------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     -----------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it
 *     and/or modify it under the terms of the GNU General Public
 *     License as published by the Free Software Foundation,
 *     either version 3 of the License, or (at your option) any
 *     later version.
 * 
 *     This program is distributed in the hope that it will be
 *     useful, but WITHOUT ANY WARRANTY; without even the implied
 *     warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *     PURPOSE.
 *     See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public
 *     License along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* LibEVM writable globals */

  /* global
       wallet_name:
         writable */

  /* global
       call_timeout:
         writable */

/* eslint-disable
     no-unused-vars */

/* eslint
     no-undef:
       "error" */
/* eslint
     no-unused-vars: [
       "error",
       { "vars":
           "local" }
     ] */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv */
const
  _argv =
    _libcrash._argv;
/* global
     _argv_url_get */
const
  _argv_url_get =
    _libcrash._argv_url_get;
/* global
     _basename */
const
  _basename =
    _libcrash._basename;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
const
  _echo =
    _libcrash._echo;
const
  _echo2 =
    _libcrash._echo2;
const
  _exit =
    _libcrash._exit;
const
  _get =
    _libcrash._get;
const
  _global_get =
    _libcrash._global_get;
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
const
  _override_set =
    _libcrash._override_set;
const
  _require =
    _libcrash._require;
const
  _set =
    _libcrash._set;
const
  _libevm_module =
    await _require(
      "libevm");
/* global
     _libevm_cmdline_parse */
const
  _libevm_cmdline_parse =
    _libevm_module._libevm_cmdline_parse;
/* global
     _libevm_global_variables */
const
  _libevm_global_variables =
    _libevm_module._libevm_global_variables;
/* global
     _libevm_app_global_variables */
const
  _libevm_app_global_variables =
    _libevm_module._libevm_app_global_variables;
/* global
     _libevm_url_parse */
const
  _libevm_url_parse =
    _libevm_module._libevm_url_parse;
/* global
     _wallet_overrides_set */
const
  _wallet_overrides_set =
    _libevm_module._wallet_overrides_set;
const
  _libevmfs_module =
    await import(
      "./libevmfs");
/* global
     _evmfs */
const
  _evmfs =
    _libevmfs_module._evmfs;
/* global
     _chunks_ccget */
/* exported
     _chunks_ccget */
const
  _ccget =
    _libevmfs_module._ccget;
/* global
     _check */
/* exported
     _check */
const
  _chunks_check =
    _libevmfs_module._chunks_check;
/* global
     _get */
/* exported
     _get */
const
  _chunks_get =
    _libevmfs_module._chunks_get;
/* global
     _index */
/* exported
     _index */
const
  _chunks_index =
    _libevmfs_module._chunks_index;
/* global
     _lock */
/* exported
     _lock*/
const
  _lock =
    _libevmfs_module._lock;
/* global
     _lengthlock*/
/* exported
 *   _lengthlock*/
const
  _lengthlock =
    _libevmfs_module._lengthlock;
/* global
     _publish*/
/* exported
     _publish*/
const
  _publish =
    _libevmfs_module._publish;
/* global
     _publish_bulk */
/* exported
     _publish_bulk */
const
  _publish_bulk =
    _libevmfs_module._publish_bulk;
/* global
     _verify */
/* exported
     _verify */
const
  _verify =
    _libevmfs_module._verify;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  _set(
    "app",
    "name",
    "evmfs.js");
  /* global
       app_opts:
         writable */
  _set(
    "app",
    "opts",
    []);
  /* global
       retries_max:
         writable */
  _set(
    "retries",
    "max",
    "");
  /* global
       call_method:
         writable */
  _set(
    "call",
    "method",
    "");
  /* global
       chunk_length:
         writable */
  _set(
    "chunk",
    "length",
    "");
  /* global
       output_file:
         writable */
  _set(
    "output",
    "file",
    "");
  /* global
       tasks_parallel:
         writable */
  _set(
    "tasks",
    "parallel",
    "");
  /* global
       api_key_path:
         writable */
  _set(
    "api_key",
    "path",
    "");
  /* global
       target_network:
         writable */
  _set(
    "target",
    "network",
    "");
  /* global
       deployments_dir:
         writable */
  _set(
    "deployments",
    "dir",
    "");
  /* global
       fs_address:
         writable */
  _set(
    "fs",
    "address",
    "");
  /* global
       fs_version:
         writable */
  _set(
    "fs",
    "version",
    "");
  /* global
       rpc_selection:
         writable */
  _set(
    "rpc",
    "selection",
    "");
  /* global
       contract_address:
         writable */
  _set(
    "contract",
    "address",
    "");
  /* global
       contract_abi_path:
         writable */
  _set(
    "contract_abi",
    "path",
    "");
  /* global
       contract_bytecode_path:
         writable */
  _set(
    "contract_bytecode",
    "path",
    "");
  /* global
       contract_compiler_output_path:
         writable */
  _set(
    "contract_compiler_output",
    "path",
    "");
  /* global
       method_objects:
         writable */
  _set(
    "method",
    "objects",
    {});
  /* global
       publication_namespace:
         writable */
  _set(
    "publication",
    "namespace",
    "");
  /* global file_hash:
       writable */
  _set(
    "file",
    "hash",
    "");
  /* global
       index_network:
         writable */
  _set(
    "index",
    "network",
    "");
  /* global
       index_end:
         writable */
  _set(
    "index",
    "end",
    "");
  /* global
       checkpoint_file_path:
         writable */
  _set(
    "checkpoint_file",
    "path",
    "");
  /* global
       chunks_files_paths:
         writable */
  _set(
    "chunks_files",
    "paths",
    []);
  const
    _global =
      _global_get();
  global[
    "quiet"] =
    "";
}

function
  _overrides_set() {
  _override_set(
    "rpc",
    "selection",
    "kirsh");
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _program =
      _basename(
        _argv[
          0]);
  const
    _text = [
      "",
      "Ethereum Virtual Machine File System",
      "",
      "Usage:",
      `  ${_program}`,
      "    [options]",
      "    <command>",
      "    ( [command-args] )",
      "",
      "  commands:",
      "    get",
      "      <resource-uri>",
      "    publish",
      "      <file-path>",
      "",
      "  networks:",
      `    '${_target_networks}'`,
      "",
      "  options:",
      "",
      "    -m <call-method>          It can be 'standalone', 'bulk' or",
      "                              'simulate'",
      `                              Default: ${call_method}`,
      "",
      "    -i <index-network>        EVM Network for the CrossChainFileSystem and",
      "                              the LengthLock contracts.",
      `                              Default: ${index_network}`,
      "",
      "    -r <retries-max>          Maximum number of retries before",
      "                              failing.",
      `                              Default: ${retries_max}`,
      "",
      "    -T <call-timeout>         Maximum number of milliseconds before",
      "                              declaring the call failed.",
      `                              Default: ${call_timeout}`,
      "",
      "    -P <tasks-parallel>       How many calls tasks perform at any",
      "    --tasks-parallel <num>    given time.",
      `                              Default: ${tasks_parallel}`,
      "",
      "  get options:",
      "",
      "    -o <output-file>          Name of the file in which to save",
      "                              the downloaded resource.",
      `                              Default: ${output_file}`,
      "",
      "  publish options:",
      "",
      "    -L                        Skip check and publish and only lock",
      "                              the file.",
      `                              Default: ${lock_only}`,
      "",
      "    -l <chunk-length>         Length of the encoded chunk.",
      "                              It can be different whether",
      "                              you are using GNU Bash or",
      "                              Javascript version of Encoding",
      "                              Tools.",
      "                              On EVM networks one can write up",
      "                              around 24.000 characters but on",
      "                              some networks it seems it's not possible",
      "                              to spend the amount of gas needed to",
      "                              write that much.",
      `                              Default: ${chunk_length}`,
      "",
      "  contract options:",
      "",
      "    -A <fs-address>           Address of the EVM file system",
      "                              on the network.",
      `                              Default: ${fs_address}`,
      "",
      "    -C <ccfs-address>         Address of the CrossChainFileSystem",
      "                              contract on the network.",
      `                              Default: ${ccfs_address}`,
      "",
      "    -V <fs-version>           Version of the target EVM file",
      "                              system.",
      `                              Default: ${fs_version}`,
      "",
      "  libevm options:",
      "",
      "    -u                        Whether to retrieve file system",
      "                              address from user directory or",
      "                              custom deployment.",
      `                              Default: ${user_level}`,
      "",
      "    -d <deployments-dir>      Contracts deployments directory.",
      `                              Default: ${deployments_dir}`,
      "",
      "    -n <network>              EVM network names. Use either name",
      "                              or Chain ID.",
      `                              Default: ${target_networks}`,
      "  credentials options:",
      "    -N <wallet-name>          Wallet name.",
      `    --wallet-name <name>      Default: ${wallet_name}`,
      "",
      "    -w <wallet-path>          Wallet path.",
      `    --wallet-path <path>      Default: ${wallet_path}`,
      "",
      "    -p <wallet-password>      Wallet password.",
      `    --wallet-password <path>  Default: ${wallet_password}`,
      "",
      "    -s <wallet-seed>          Wallet seed path.",
      `    --wallet-seed <seed>      Default: ${wallet_seed}`,
      "",
      "    -k <api-key>              Etherscan-like service key.",
      `    --api-key <path>          Default: ${api_key}`,
      "",
      "  application options:",
      "",
      "    -W <cache-dir>            Work directory.",
      `                              Default: ${cache_dir}`,
      "",
      "    -h, --help               This message.",
      "",
      "    -c, --color              Enable color output",
      "",
      "    -v, --verbose            Enable verbose output",
    ];
  for ( _line of _text ) {
    _echo(
      _line);
  }
  _exit(
    _exit_code);
}

function
  _config_show() {
  /* LibEVM-defined global variables */
  /* global
       api_key */
  /* global
       wallet_address */
  /* global
       wallet_password */
  /* global
       wallet_path */
  /* global
       wallet_seed */
  let
    _line;
  const
    _program =
      _basename(
        _argv[
          0]);
  const
    _text = [
      `${_program} configuration:`,
      `                  Call date:   ${call_date}`,
      `            Runtime environment:   ${runtime_environment}`,
      `                  Target command:   ${target_command}`,
      `                      Target key:   ${target_key}`,
      `                    Target value:   ${target_value}`,
      `                   Index network:   ${target_network}`,
      `                     Call method:   ${target_network}`,
      `                    Chunk length:   ${chunk_length}`,
      `           Publication options:`,
      `                       Lock only:   ${lock_only}`,
      `                   Skip encoding:   ${encoding_skip}`,
      "              Download options:",
      `                     Output type:   ${output_type}`,
      "              Contract options:",
      `             File system address:   ${fs_address}`,
      ` Cross-chain file system address:   ${ccfs_address}`,
      `             File system version:   ${fs_version}`,
      `           Credentials options:`,
      `                     Wallet name:   ${wallet_name}`,
      `                  Wallet address:   ${wallet_address}`,
      `                     Wallet path:   ${wallet_path}`,
      `                     Wallet seed:   ${wallet_seed}`,
      `                         API Key:   ${api_key}`,
      "                LibEVM options:",
      `                      User level:   ${user_level}`,
      `           Deployments directory:   ${deployments_dir}`,
      `                  Target network:   ${target_network}`,
      `               Network options:`,
      `                 Maximum retries:   ${retries_max}`,
      `                    Call timeout:   ${call_timeout}`,
      `                  Parallel tasks:   ${tasks_parallel}`,
      `           Application options:`,
      `                 Cache directory:   ${cache_dir}`,
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

async function
  _main() {
  let
    _msg,
    _result,
    _results;
  try {
    const
      _overrides_set_up =
        await _overrides_set();
  }
  catch(
    _error) {
    _msg =
      "Error setting overrides.";
    _msg_error(
      _msg,
      0);
  }
  _config_show();
  const
    app_opts = [
      target_command,
      fs_address,
      ccfs_address,
      fs_version,
      deployments_dir,
      wallet_name,
      wallet_path,
      wallet_password,
      wallet_seed,
      target_network,
      api_key,
      call_method,
      index_network,
      retries_max,
      call_timeout,
      lock_only,
      chunk_length,
      encoding_skip,
      tasks_parallel,
      cache_dir,
      user_level,
      output_file,
      target_key,
      target_value
    ];
  try {
    _results =
      await _evmfs.apply(
        null,
        app_opts);
  }
  catch(
    _error) {
    _msg =
      "Error running '_evmfs' " +
      "with arguments:";
    _msg_error(
      _msg,
      0);
    _echo2(
      app_opts);
    _echo2(
      _error);
    throw _error;
  }
  const
    _results_type =
      typeof(
        _results);
  if ( _results_type == "bigint" ) {
    _echo(
      _results.toString());
  }
  else if ( _results_type == "string" ) {
    _echo(
      _results);
  }
  else if ( _results_type == "object" ) {
    for ( _result of _results ) {
      _echo(
        _result);
    }
  }
  else if ( _results_type == "undefined" ) {
    _msg =
      `No results.`;
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  else {
    _msg =
      "Error retrieving results for command. " +
      `Type of return: '${_results_type}'.`;
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
}

async function 
  _cmdline_parse() {
  let
    _help_display;
  const
    _global =
      _global_get();
  const
    _argv_args = {
      "booleans": [
        "h",
        "help",
        "Q",
        "with-colons",
        "v",
        "verbose"
      ],
      "string":
        true
    };
  const
    _argv =
      await _argv_get(
        _argv_args);
  const
    _options =
      _argv[
        "_"];
  _global[
    "quiet"] = 
    "y";
  runtime_environment =
    "node";
  if ( _argv[
         "h"] ||
       _argv[
         "help"] ) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    _global[
      "quiet"] =
      "n";
    await _overrides_set();
    _usage(
      0);
  }
  if ( _argv[
         "Q"] ||
       _argv[
         "with-colons"] ) {
    with_colons =
      "y";
  }
  else {
    with_colons =
      "n";
  }
  if ( typeof(
       _argv) != "undefined" &&
       0 < _argv[
             "_"].length ) {
    target_command =
      _argv[
        "_"][
          0];
  }
  if ( typeof(
       _argv) != "undefined" &&
       1 < _argv[
             "_"].length ) {
    command_key =
      _argv[
        "_"][
          1];
  }
  if ( typeof(
       _argv) != "undefined" &&
       2 < _argv[
             "_"].length ) {
    command_value =
      _argv[
        "_"][
          2];
  }
  if ( "R" in _argv ) {
    rpc_selection =
      _argv[
        "R"];
  }
  if ( "rpc-selection" in _argv ) {
    rpc_selection =
      _argv[
        "rpc-selection"];
  }
  if ( "S" in _argv ) {
    explorer_selection =
      _argv[
        "S"];
  }
  if ( "explorer-selection" in _argv ) {
    explorer_selection =
      _argv[
        "explorer-selection"];
  }
  if ( "r" in _argv ) {
    retries_max =
      _argv[
        "r"];
  }
  if ( "retries-max" in _argv ) {
    retries_max =
      _argv[
        "retries-max"];
  }
  if ( "u" in _argv ) {
    measure_unit =
      _argv[
        "u"];
  }
  if ( "measure-unit" in _argv ) {
    measure_unit =
      _argv[
        "measure-unit"];
  }
  if ( "l" in _argv ) {
    balance_lifespan =
      _argv[
        "l"];
  }
  if ( "balance-lifespan" in _argv ) {
    balance_lifespan =
      _argv[
        "balance-lifespan"];
  }
  if ( "a" in _argv ) {
    networks_all =
      "y";
  }
  if ( "networks-all" in _argv ) {
    networks_all =
      "y";
  }
  if ( "P" in _argv ) {
    tasks_parallel =
      _argv[
        "P"];
  }
  if ( "tasks-parallel" in _argv ) {
    tasks_parallel =
      _argv[
        "tasks-parallel"];
  }
  if ( "Q" in _argv ) {
    qr_support =
      _argv[
        "Q"];
  }
  if ( "qr-support" in _argv ) {
    qr_support =
      _argv[
        "qr-support"];
  }
  if ( "o" in _argv ) {
    output_type =
      _argv[
        "o"];
  }
  if ( "output-type" in _argv ) {
    output_type =
      _argv[
        "output-type"];
  }
  if ( "t" in _argv ) {
    currency_type =
      _argv[
        "t"];
  }
  if ( "currency-type" in _argv ) {
    currency_type =
      _argv[
        "currency-type"];
  }
  if ( "C" in _argv ) {
    currency_address =
      _argv[
        "C"];
  }
  if ( "currency" in _argv ) {
    currency_address =
      _argv[
        "currency"];
  }
  _libevm_cmdline_parse(
    _argv);
  if ( _argv[
         "v"] ||
       _argv[
         "verbose"]) {
    _global[
      "verbose"] =
      true;
  }
  if ( verbose ) {
    _global[
      "quiet"] =
      "n";
  }
}

function
  _url_parse() {
  const
    _argv =
      _argv_url_get();
  runtime_environment =
    "browser";
  wallet_name =
    _argv_url_get(
      "wallet_name")[
        0];
  rpc_selection =
    _argv_url_get(
      "rpc_selection")[
        0];
  explorer_selection =
    _argv_url_get(
      "explorer_selection")[
        0];
  retries_max =
    _argv_url_get(
      "retries_max")[
        0];
  measure_unit =
    _argv_url_get(
      "measure_unit")[
        0];
  balance_lifespan =
    _argv_url_get(
      "balance_lifespan")[
        0];
  networks_all =
    _argv_url_get(
      "networks_all")[
        0];
  tasks_parallel =
    _argv_url_get(
      "tasks_parallel")[
        0];
  _set(
    "qr",
    "support",
    _argv_url_get(
      "qr_support")[
        0]);
  output_type =
    _argv_url_get(
      "output_type")[
        0];
  currency_address =
    _argv_url_get(
      "currency_address")[
        0];
  config_dir =
    _argv_url_get(
      "config_dir")[
        0];
  cache_dir =
    _argv_url_get(
      "cache_dir")[
        0];
  _libevm_url_parse();
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    _argv_url_get(
      "quiet");
  if ( _global[
         "quiet"].length === 0 ) {
    _global[
      "quiet"] =
      "n";
  }
}

_echo(
  "EVMFS Init.");
_global_variables();
_libevm_global_variables();
_libevm_app_global_variables();
_echo(
  "Finished setting EVMFS globals.");
if ( await _cmdline_check(
       "evmfs.js") ||
     await _cmdline_check(
       "evmfs") ) {
  _echo(
    "Running 'evmfs' from the command line.");
  _cmdline_parse();
}
else {
  _echo(
    "Running 'evmfs' from a web browser.");
  _url_parse();
}
_main();
