#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evmfs.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* LibEVM writable globals */

  /* global
       wallet_name:
         writable */


/* eslint-disable
     no-unused-vars */

/* eslint
     no-undef:
       "error" */
/* eslint
     no-unused-vars: [
       "error",
       { "vars":
           "local" }
     ] */

const
  _libcrash =
    require(
      "crash-js");
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _process_exit */
const
  _process_exit =
    _libcrash._process_exit();
const
  _ccget_module =
    require(
      "./lib/evmfs.js.ccget");
/* global
     _ccget */
/* exported
     _ccget */
const
  _ccget =
    _ccget_module._ccget;
const
  _check_module =
    require(
      "./lib/evmfs.js.check");
/* global
     _check */
/* exported
     _check */
const
  _check =
    _check_module._check;
const
  _get_module =
    require(
      "./lib/evmfs.js.get");
/* global
     _get */
/* exported
     _get */
const
  _get =
    _get_module._get;
const
  _index_module =
    require(
      "./lib/evmfs.js.index");
/* global
     _index */
/* exported
     _index */
const
  _index =
    _index_module._index;
const
  _lock_module =
    require(
      "./lib/evmfs.js.lock");
/* global
     _lock */
/* exported
     _lock*/
const
  _lock =
    _lock_module._lock;
const
  _lengthlock_module =
    require(
      "./lib/evmfs.js.lengthlock");
/* global
     _lengthlock*/
/* exported
 *   _lengthlock*/
const
  _lengthlock =
    _lengthlock_module._lengthlock;
const
  _publish_module =
    require(
      "./lib/evmfs.js.publish");
/* global
     _publish*/
/* exported
     _publish*/
const
  _publish =
    _publish_module._publish;
const
  _publish_bulk_module =
    require(
      "./lib/evmfs.js.publish.bulk");
/* global
     _publish_bulk */
/* exported
     _publish_bulk */
const
  _publish_bulk =
    _publish_bulk_module._publish_bulk;
const
  _verify_module =
    require(
      "./lib/evmfs.js.verify");
/* global
     _verify */
/* exported
     _verify */
const
  _verify =
    _verify_module._verify;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "evmfs.js";
  /* global
       app_opts:
         writable */
  app_opts =
    [];
  /* global
       retries_max:
         writable */
  retries_max =
    "";
  /* global
       api_key_path:
         writable */
  api_key_path =
    "";
  /* global
       target_network:
         writable */
  target_network =
    "";
  /* global
       deployments_dir:
         writable */
  deployments_dir =
    "";
  /* global
       fs_version:
         writable */
  fs_version =
    "";
  /* global
       rpc_selection:
         writable */
  rpc_selection =
    "";
  /* global
       contract_address:
         writable */
  contract_address =
    "";
  /* global
       contract_abi_path:
         writable */
  contract_abi_path =
    "";
  /* global
       contract_bytecode_path:
         writable */
  contract_bytecode_path =
    "";
  /* global
       contract_compiler_output_path:
         writable */
  contract_compiler_output_path =
    "";
  /* global
       method_objects:
         writable */
  method_objects =
    {};
  /* global
       publication_namespace:
         writable */
  publication_namespace =
    "";
  /* global file_hash:
       writable */
  file_hash =
    "";
  /* global
       index_start:
         writable */
  index_start =
    "";
  /* global
       index_end:
         writable */
  index_end =
    "";
  /* global
       checkpoint_file_path:
         writable */
  checkpoint_file_path =
    "";
  /* global
       chunks_files_paths:
         writable */
  chunks_files_paths =
    [];
  /* global
       quiet:
         writable */
  quiet =
    "";
}

async function
  _evmfs(
    _stub
  ) {
  let
    _msg;
  _msg =
    `stub '${_stub}'.`;
  _msg =
    _msg + _msg;
  _msg_info(
    _msg);
}

function
  _overrides_set() {
  if ( rpc_selection == "" ) {
    rpc_selection =
      "kirsh";
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;

  const
    _hi = `

  options:
     -m <call_method>       It can be 'standalone', 'bulk' or
                            'simulate'
                            Default: ${call_method}
     -i <index_network>     EVM Network for the CrossChainFileSystem and
                            the LengthLock contracts.
                            Default: ${index_network}
     -r <retries_max>       Maximum number of retries before
                            failing.
                            Default: ${retries_max}
     -T <call_timeout>      Maximum number of milliseconds before
                            declaring the call failed.
                            Default: ${call_timeout}
     -P <tasks_parallel>    How many calls tasks perform at any
                            given time
                            Default: ${tasks_parallel}

  get options:
     -o <output_file>       Name of the file in which to save
                            the downloaded resource.
                            Default: ${output_file}

  publish options:
     -L                     Skip check and publish and only lock
                            the file.
                            Default: ${lock_only}
     -l <chunk-length>      Length of the encoded chunk.
                            On EVM networks one can write up to
                            around 24.000 characters
                            but on some network it seems it
                            is not possible to spend the amount
                            of gas needed to write that much.
                            Default: ${chunk_length}

  contract options:
     -A <fs_address>        Address of the EVM file system
                            on the network.
                            Default: ${fs_address}
     -C <ccfs_address>      Address of the CrossChainFileSystem
                            contract on the network.
                            Default: ${ccfs_address}
     -V <fs_version>        Version of the target EVM file
                            system.
                            Default: ${fs_version}
  libevm options
     -u                     Whether to retrieve file system
                            address from user directory or custom
                            deployment.
                            Default: ${user_level}
     -d <deployments_dir>   Contracts deployments directory.
                            Default: ${deployments_dir}
     -n <network>           EVM network name. Use either name
                            or ID.
                            Default: ${target_network}
  credentials options:
     -N <wallet_name>       Wallet name.
                            Default: ${wallet_name}
     -w <wallet_path>       Wallet path.
                            Default: ${wallet_path}
     -p <wallet_password>   Wallet password.
                            Default: ${wallet_password}
     -s <wallet_seed>       Wallet seed path.
                            Default: ${wallet_seed}
     -k <api_key>           Etherscan-like service key.
                            Default: ${api_key}

  application options:
     -W <cache-dir>         Work directory.
                            Default: ${cache_dir}
	  `;
  const
    _text = [
      "",
      "Ethereum Virtual Machine File System",
      "",
      "Usage:",
      `  ${app_name}`,
      "    [options]",
      "    <command>",
      "    ( [command-args] )",
      "",
      "  commands:",
      "    get",
      "      <resource-uri>",
      "    publish",
      "      <file-path>",
      "",
      "  networks:",
      `    '${_target_networks}`',
      "",
      "  options:",
      "",
     -m <call_method>       It can be 'standalone', 'bulk' or
                            'simulate'
                            Default: ${call_method}
     -i <index_network>     EVM Network for the CrossChainFileSystem and
                            the LengthLock contracts.
                            Default: ${index_network}
     -r <retries_max>       Maximum number of retries before
                            failing.
                            Default: ${retries_max}
     -T <call_timeout>      Maximum number of milliseconds before
                            declaring the call failed.
                            Default: ${call_timeout}
      "    -P <tasks-parallel>       How many calls tasks perform at any",
      "    --tasks-parallel <num>    given time.
      `                              Default: ${tasks_parallel}
      "    -H <gnupg-home>,          GNUPG home directory.",
      `    --gnupg-home <dir>        Default: ${gnupg_home}`,
      "",
      "    -K <gnupg-public>         Public keys keyring GNUPG",
      "    --gnupg-public <dir>      home directory.",
      `                              Default: ${gnupg_public}`,
      "    -t <key-type>             It can be empty, 'public'",
      "    --key-type <type>         or 'private'.",
      `                              Default: ${key_type}`,
      "    -Q                        If enabled, passes the '--with-colons'",
      "    --with-colons             serializing option to GPG.",
      `                              Default: ${with_colons}`,
      "",
      "  key creation options:",
      "    -P <passphrase>           Key passphrase (for 'new' command).",
      `    --passphase <passphrase>  Default: ${key_passphrase}`,
      "",
      "    -C <comment>              Key comment (for 'new' command).",
      `    --comment <comment>       Default: ${key_comment}`,
      "",
      "    -S <y/n>                  If enabled, automatically publishes",
      "    --publish-key <y/n>       the newly key on the EVM OpenPGP",
      "                              Key Server.",
      `                              Default: ${key_publish}`,
      "",
      "  export options:",
      "    -a <address>              Export key corresponding to a specific address.",
      `    --address <address>       Default: ${wallet_address}`,
      "",
      "  list options:",
      "    -o <output-type>          It can be empty, 'fingerprint',",
      "                              'name' or 'email' or 'full'.",
      `                              Default: ${output_type}`,
      "",
      "  receive options:",
      "    -i <input-type>           It can be 'auto', 'address',",
      "    --input-type <type>       'contact'.",
      `                              Default: ${input_type}`,
      "",
      "  credentials options:",
      "    -N <wallet-name>          Wallet name.",
      `    --wallet-name <name>      Default: ${wallet_name}`,
      "",
      "    -w <wallet-path>          Wallet path.",
      `    --wallet-path <path>      Default: ${wallet_path}`,
      "",
      "    -p <wallet-password>      Wallet password.",
      `    --wallet-password <path>  Default: ${wallet_password}`,
      "",
      "    -s <wallet-seed>          Wallet seed path.",
      `    --wallet-seed <seed>      Default: ${wallet_seed}`,
      "",
      "    -k <api-key>              Etherscan-like service key.",
      `    --api-key <path>          Default: ${api_key}`,
      "",
      "",
      "  application options:",
      "",
      "    -h, --help               This message.",
      "",
      "    -c, --color              Enable color output",
      "",
      "    -v, --verbose            Enable verbose output",
    ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  _process_exit(
    _exit_code);
}

function 
  _cmdline_parse() {
  quiet = 
    "y";

}

if ( _cmdline_check(
       "evmfs.js") ) {
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    retries_max,
    api_key_path,
    target_network,
    deployments_dir,
    fs_version,
    rpc_selection,
    contract_address,
    contract_abi_path,
    contract_bytecode_path,
    contract_compiler_output_path,
    method_objects,
    publication_namespace,
    file_hash,
    index_start,
    index_end,
    checkpoint_file_path,
    chunks_files_paths,
  ];
  _evmfs.apply(
    null,
    app_opts);
}

module.exports = {
  _chain_id_read:
    _chain_id_read,
  _fs_address_read:
    _fs_address_read,
  _ccget:
    _ccget,
  _chunk_check:
    _chunk_check,
  _chunk_get:
    _chunk_get,
  _chunk_publish:
    _chunk_publish,
  _chunks_publish_bulk:
    _chunks_publish_bulk,
  _check:
    _check,
  _index:
    _index,
  _get:
    _get,
  _lengthlock:
    _lengthlock,
  _lock:
    _lock,
  _publish:
    _publish,
  _publish_bulk:
    _publish_bulk,
  _references_read:
    _references_read,
  _verify:
    _verify
};
