#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _check_module =
    require(
      "./check");
const
  _ccget_module =
    require(
      "./ccget");
const
  _get_module =
    require(
      "./get");
const
  _index_module =
    require(
      "./index");
const
  _lengthlock_module =
    require(
      "./lengthlock");
const
  _lock_module =
    require(
      "./lock");
const
  _publish_module =
    require(
      "./publish");
const
  _publish_bulk_module =
    require(
      "./publish.bulk");
const
  _verify_module =
    require(
      "./verify");

module.exports = {
  _ccget:
    _ccget_module,
  _check:
    _check_module,
  _index:
    _index_module,
  _lengthlock:
    _lengthlock_module,
  _lock:
    _lock_module,
  _get:
    _get_module,
  _publish:
    _publish_module,
  _publish_bulk:
    _publish_bulk_module,
  _verify:
    _verify_module,
};
